github_rest_token: "github_xxx" # null or "github_xxx"

user_name: "xxx"
email_address: "xxx@yyy.com"
password: "xxxxx"
port: 80

llm_api_key: "sk-xxxxxx"
base_url: "xxxxx"
evaluation_model: deepseek-chat